apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ns.networkservicemesh.io: icmp-responder?app=icmp
  creationTimestamp: "2020-02-08T14:28:56Z"
  generation: 1
  name: icmp-responder-nsc
  namespace: default
  resourceVersion: "289253"
  selfLink: /apis/apps/v1/namespaces/default/deployments/icmp-responder-nsc
  uid: 4d067abc-fe87-4fa9-94ab-c0881d7b1d39
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      networkservicemesh.io/app: icmp-responder-nsc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        networkservicemesh.io/app: icmp-responder-nsc
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: alpine:latest
        imagePullPolicy: Always
        name: alpine-img
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: MONITOR_DNS_CONFIGS
          value: "true"
        - name: UPDATE_API_CLIENT_SOCKET
          value: /etc/coredns/client.sock
        - name: NS_NETWORKSERVICEMESH_IO
          value: icmp-responder?app=icmp
        image: networkservicemesh/nsm-monitor:master
        imagePullPolicy: IfNotPresent
        name: nsm-dns-monitor
        resources:
          limits:
            networkservicemesh.io/socket: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: nsm-coredns-volume
      - args:
        - -conf
        - /etc/coredns/Corefile
        env:
        - name: USE_UPDATE_API
          value: "true"
        - name: UPDATE_API_CLIENT_SOCKET
          value: /etc/coredns/client.sock
        image: networkservicemesh/nsm-coredns:master
        imagePullPolicy: IfNotPresent
        name: nsm-coredns
        resources:
          limits:
            networkservicemesh.io/socket: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: nsm-coredns-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: NS_NETWORKSERVICEMESH_IO
          value: icmp-responder?app=icmp
        - name: NSM_NAMESPACE
          value: nsm-system
        - name: JAEGER_AGENT_HOST
          value: jaeger.nsm-system
        - name: TRACER_ENABLED
          value: "false"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        image: networkservicemesh/nsm-init:master
        imagePullPolicy: IfNotPresent
        name: nsm-init-container
        resources:
          limits:
            networkservicemesh.io/socket: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nsc-acc
      serviceAccountName: nsc-acc
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nsm-coredns-volume
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2020-02-08T14:30:14Z"
    lastUpdateTime: "2020-02-08T14:30:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-08T14:28:56Z"
    lastUpdateTime: "2020-02-08T14:30:17Z"
    message: ReplicaSet "icmp-responder-nsc-79c7697b78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
