apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-02-08T14:28:56Z"
  generateName: icmp-responder-nsc-79c7697b78-
  labels:
    networkservicemesh.io/app: icmp-responder-nsc
    pod-template-hash: 79c7697b78
  name: icmp-responder-nsc-79c7697b78-64rlb
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: icmp-responder-nsc-79c7697b78
    uid: 8421065c-9b8e-4cce-9b6b-92e9b9cf3642
  resourceVersion: "289232"
  selfLink: /api/v1/namespaces/default/pods/icmp-responder-nsc-79c7697b78-64rlb
  uid: c043295e-ebcb-40f7-90f3-2be8a25313de
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: alpine:latest
    imagePullPolicy: Always
    name: alpine-img
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: nsc-acc-token-ch8dq
      readOnly: true
  - env:
    - name: MONITOR_DNS_CONFIGS
      value: "true"
    - name: UPDATE_API_CLIENT_SOCKET
      value: /etc/coredns/client.sock
    - name: NS_NETWORKSERVICEMESH_IO
      value: icmp-responder?app=icmp
    image: networkservicemesh/nsm-monitor:master
    imagePullPolicy: IfNotPresent
    name: nsm-dns-monitor
    resources:
      limits:
        networkservicemesh.io/socket: "1"
      requests:
        networkservicemesh.io/socket: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: nsm-coredns-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: nsc-acc-token-ch8dq
      readOnly: true
  - args:
    - -conf
    - /etc/coredns/Corefile
    env:
    - name: USE_UPDATE_API
      value: "true"
    - name: UPDATE_API_CLIENT_SOCKET
      value: /etc/coredns/client.sock
    image: networkservicemesh/nsm-coredns:master
    imagePullPolicy: IfNotPresent
    name: nsm-coredns
    resources:
      limits:
        networkservicemesh.io/socket: "1"
      requests:
        networkservicemesh.io/socket: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: nsm-coredns-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: nsc-acc-token-ch8dq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: NS_NETWORKSERVICEMESH_IO
      value: icmp-responder?app=icmp
    - name: NSM_NAMESPACE
      value: nsm-system
    - name: JAEGER_AGENT_HOST
      value: jaeger.nsm-system
    - name: TRACER_ENABLED
      value: "false"
    - name: JAEGER_AGENT_PORT
      value: "6831"
    image: networkservicemesh/nsm-init:master
    imagePullPolicy: IfNotPresent
    name: nsm-init-container
    resources:
      limits:
        networkservicemesh.io/socket: "1"
      requests:
        networkservicemesh.io/socket: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: nsc-acc-token-ch8dq
      readOnly: true
  nodeName: ip-172-31-36-68
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: nsc-acc
  serviceAccountName: nsc-acc
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: nsm-coredns-volume
  - name: nsc-acc-token-ch8dq
    secret:
      defaultMode: 420
      secretName: nsc-acc-token-ch8dq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-08T14:30:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-08T14:30:14Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-08T14:30:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-08T14:28:56Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bdda8b9afdf98f6c8c0f33150175ee32a0d7851d108bc37e7d8f206453313a7e
    image: alpine:latest
    imageID: docker-pullable://alpine@sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
    lastState: {}
    name: alpine-img
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-02-08T14:30:13Z"
  - containerID: docker://89821258380b0b74428391aa245b3f22db79c979a8d3603f2ed33d49d0a19297
    image: networkservicemesh/nsm-coredns:latest
    imageID: docker://sha256:7055bf561dbbefac4059b8bf12ff239ff136efa6f45bfae1eba3f31fb5aa21c5
    lastState: {}
    name: nsm-coredns
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-02-08T14:30:14Z"
  - containerID: docker://d14aaae302783c7149820610997dc93fed164039390537de139e608f4ebd1312
    image: networkservicemesh/nsm-monitor:latest
    imageID: docker://sha256:e3dff2f2caaa31828a24b5639da247b7e00c7aad08b370fe9ba7bc2eb67296b7
    lastState: {}
    name: nsm-dns-monitor
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-02-08T14:30:13Z"
  hostIP: 172.31.36.68
  initContainerStatuses:
  - containerID: docker://5108d22e9b9658ead8d0e9ab522af14ba547bd37ed69e82d95e7612efe02a5e6
    image: networkservicemesh/nsm-init:latest
    imageID: docker://sha256:580a13bf7e9896f923defe74e4b12cccf4a4e49dcd84359c737df2e8482cd10c
    lastState: {}
    name: nsm-init-container
    ready: true
    restartCount: 1
    state:
      terminated:
        containerID: docker://5108d22e9b9658ead8d0e9ab522af14ba547bd37ed69e82d95e7612efe02a5e6
        exitCode: 0
        finishedAt: "2020-02-08T14:30:02Z"
        reason: Completed
        startedAt: "2020-02-08T14:29:51Z"
  phase: Running
  podIP: 192.168.0.23
  podIPs:
  - ip: 192.168.0.23
  qosClass: BestEffort
  startTime: "2020-02-08T14:28:57Z"
